### PR TITLE
[FIX] update vismotion demo

### LINKED ISSUE #512: [BUG]: `bidsResults` does not work if default model
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

in `vismotion` demo: with `opt.model.file = '';` should read `model-defaultVisMotion_smdl.json`

### Current Behavior

when running `bidsResults(opt);` see error below

### Error message

```
Error using spm_jsonread
Empty JSON.

Error in getRFXdir (line 20)
  model = spm_jsonread(opt.model.file);

Error in bidsResults>bidsResultsdataset (line 228)
    result.dir = fullfile(getRFXdir(opt), result.Contrasts.Name);

Error in bidsResults (line 169)
        [matlabbatch, result] = bidsResultsdataset(opt, iNode);
```

### Environment

```markdown
- OS: macOS
- Matlab: 2017b
- SPM: 7487
```

### Anything else?

branch `dev` commit `238bf72a6ea3e699aa983288611d4b1842c1c8f7`

### PR DESCRIPTION
**Pull request by Remi-Gau**
aims to fix #512

### CODE REVIEW

File: demos/MoAE/moae_01_preproc.m [hunk 1]
```diff
@@ -9,10 +9,8 @@
 download_data = false;
 clean = false;
 
-try
-  run ../../initCppSpm.m;
-catch
-end
+addpath(fullfile(pwd, '..', '..'));
```
Comment (Remi-Gau) [inline demos/MoAE/moae_01_preproc.m:12]: ignore those "init" changes, they are unrelated to the fix.

File: demos/vismotion/vismotion_demo.sh [hunk 2]
```diff
@@ -0,0 +1,57 @@
+#! /user/bin/bash
```
Comment (Remi-Gau) [inline demos/vismotion/vismotion_demo.sh:1]: @marcobarilari 

You might like this bash script.

File: src/workflows/stats/bidsResults.m [hunk 3]
```diff
@@ -121,7 +121,12 @@
 
   opt.dir.output = opt.dir.stats;
 
-  [~, opt] = setUpWorkflow(opt, 'computing GLM results');
+  [BIDS, opt] = setUpWorkflow(opt, 'computing GLM results');
+
+  if isempty(opt.model.file)
```
Comment (Remi-Gau) [inline src/workflows/stats/bidsResults.m:126]: That's where the  main error was coming from. 

I had not thought that it would be possible to run Results and RFX with the default model. So now that should be possible.

**Comment by Remi-Gau** [comment]
@marcobarilari 

When all the test pass I will merge and ask you to test the bash script to see if you can run the whole "datalad" pipeline as well:
[
[demos/vismotion/vismotion_demo.sh](https://github.com/cpp-lln-lab/CPP_SPM/pull/513/files/a9d7dffa8d0ae61100cb89de0d7dfc951f7d064a#diff-4a13b2ad5964e7c8d645f0602b8423c91e3b77dcf23ee8ce4b20618ae3b3c7a2)](https://github.com/cpp-lln-lab/CPP_SPM/pull/513/files/a9d7dffa8d0ae61100cb89de0d7dfc951f7d064a#diff-4a13b2ad5964e7c8d645f0602b8423c91e3b77dcf23ee8ce4b20618ae3b3c7a2)

**Comment by marcobarilari** [comment]
Hey! Thanks yes I like the bash script 😂 so can I  this one now?

**Comment by Remi-Gau** [comment]
> Hey! Thanks yes I like the bash script joy so can I this one now?

yup just try to run it see if if goes through the whole thing without a hitch
