### PR TITLE
[FIX] make sure GLM figures are saved

### LINKED ISSUE #329: is _design_after_estimation.png not used anymore?
previously when I ran `bidsFFX` function, this png file was created for before/after estimation and saved in for example `ffx_space-MNI_FWHM-0` folder. but now (maybe due to the `ffx` folder naming changed recently?), I cannot find it. 
Now it is not saved or found not-useful?

### PR DESCRIPTION
**Pull request by Remi-Gau**
fixes #329 

@CerenB 

I think the issue came when I was trying to fix some stuff with some githuib action failing: when running some test with github action it makes no sense to try to plot figures so I mucking about with this at the time. I forgot to revert that change.

Let's see if changes this does make the test crash...

Now the output will also directly be saved into the GLM folder

### CODE REVIEW

File: src/batches/setBatchPrintFigure.m [hunk 1]
```diff
@@ -15,7 +15,7 @@
   %
   % :returns: - :matlabbatch: (structure) The matlabbatch ready to run the spm job
 
-  if ~spm('CmdLine', true)
```
Comment (Remi-Gau) [inline src/batches/setBatchPrintFigure.m:18]: just one extra `~` and the world collapses. :wink:

**Review by CerenB — APPROVED** [review]
