### PR TITLE
[FIX] support globbing patterns to specify conditions in design matrix

### LINKED ISSUE #517: Enhance transformers capabilities
- [x] stimulus onsets: add x to odd events, add y to even events
- [x] duration changed to 1.0 sec for tactile stim (duration recorded for visual or auditory vary ~ 0.01 or 0.001 sec)
- [x] concatenate two columns in the tsv to change the name of trial_types

### LINKED ISSUE #711: [ENH]: Concatenate trial_types when several instances to create a "blocked" trial type
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New feature

In the event of trials that are split into multiple lines in the  events.tsv file; but belong to the same and unique trial (eg. below "IN_PUFF" is one trial that lasts about 8 secs but is split into 20 lines). 
Add a transformer that will concatenate these events into a single one. 
Careful : add a feature to specify which trials should be concatenated or not (if a user does not want to concatenate all but just for instance "IN_PUFF" trials). 

```tsv
onset	duration	trial_type
0.000	1.358	BASE
1.358	0.401	IN_PUFF
1.759	0.402	IN_PUFF
2.161	0.421	IN_PUFF
2.582	0.401	IN_PUFF
2.983	0.402	IN_PUFF
3.385	0.421	IN_PUFF
3.806	0.401	IN_PUFF
4.207	0.402	IN_PUFF
4.609	0.421	IN_PUFF
5.030	0.401	IN_PUFF
5.431	0.402	IN_PUFF
5.833	0.421	IN_PUFF
6.254	0.401	IN_PUFF
6.655	0.402	IN_PUFF
7.057	0.421	IN_PUFF
7.478	0.401	IN_PUFF
7.879	0.402	IN_PUFF
8.281	0.421	IN_PUFF
8.702	0.402	IN_PUFF
9.104	0.402	IN_PUFF
9.506	2.180	ISI
```

### LINKED ISSUE #712: [ENH]: Add modelization as 1 beta per trial
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New feature

For further MVPA analyses, need to have conditions modeled as 1 beta per trial (and not 1 per run per condition). 
To do this, might use a transformer that will add a column to the tsv file that is "trial_nb" for instance.

### Unclear documentation

_No response_

### PR DESCRIPTION
**Pull request by Remi-Gau**
closes #517 
closes #711 
closes #712 

- update bids matlab to use new transformers
- support globbing patterns to specify conditions in design matrix
- refactor
- add demo

what to review:

- run this demo: https://github.com/cpp-lln-lab/CPP_SPM/pull/716/files#diff-057149ac6518528990698a9edd3d0c7808bdd0db0f6b663600087acf54eca98a
- is the doc on the main function that applies the transformation to an events.tsv to generate the mat files used by SPM to create the GLM clear enough? https://cpp-spm--716.org.readthedocs.build/en/716/statistics.html#src.subject_level.convertOnsetTsvToMat

### CODE REVIEW

File: demos/transformers/split_by_trials.m [hunk 1]
```diff
@@ -0,0 +1,111 @@
+% In this example we use a matlab script to generate a series of transformations
+% and apply them to the content of a TSV file.
+%
+% This also shows how to edit the bids stats model directly,
+% so you can directly "paste" the series of transformations into the JSON
+% of your BIDS stats model.
+%
+% ---
```
Comment (Remi-Gau) [inline demos/transformers/split_by_trials.m:8]: it is not clear that ....

**Review by Remi-Gau — COMMENTED** [review]
LGTM
